name: Tests

on:
  push:
    paths-ignore:
      - "**.md"
      - "docs/**"
  pull_request:
    paths-ignore:
      - "**.md"
      - "docs/**"
  schedule:
    - cron: "0 0 * * 1"

concurrency:
  group: tests-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        php: ["8.2", "8.3", "8.4"]
        laravel: ["^11.41", "^12.0"]
        dependencies:
          - "lowest"
          - "highest"

    name: "PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} ${{ matrix.dependencies == 'highest' && '↑' || '↓' }}"

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, json, libxml, mbstring, zip
          tools: composer:v2
          coverage: none

      - name: Check Composer configuration
        run: composer validate

      - name: Install lowest dependencies
        if: matrix.dependencies == 'lowest'
        run: |
          composer require "illuminate/support=${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-lowest --prefer-dist --no-interaction --no-progress

      - name: Install highest dependencies
        if: matrix.dependencies == 'highest'
        run: |
          composer require "illuminate/support=${{ matrix.laravel }}" --no-interaction --no-update
          composer update --prefer-dist --no-interaction --no-progress

      - name: Check PSR-4 mapping
        run: composer dump-autoload --optimize --strict-psr

      - name: Execute tests
        run: composer test
